version: "3"

services:
  back_ze:
    build:
      context: .
    ports:
      - '3000:3000'
    container_name: back_ze
    restart: always
    volumes:
      - ./:/usr/src/node-api/
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    command: sh -c "npm install && npm run build && npm run start:prod"
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ze
